[package]
name = "opaque_allocator_api"
version = "1.3.0"
edition = "2024"

[features]
default = ["std"]
std = []
nightly = []

[dependencies]

[dependencies.opaque_polyfill]
version = "1.3.0"
path = "../opaque_polyfill"
