mod test_shift_remove_entry_get;
mod test_shift_remove_entry_preserves_order;
mod test_shift_remove_entry_len;
mod test_shift_remove_entry_contains_key;
mod test_shift_remove_entry_get_mut;
mod test_shift_remove_entry_get_key_value;