[package]
name = "opaque_vec"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.opaque_alloc]
version = "0.1.0"
path = "../opaque_alloc"

[features]
panic_immediate_abort = []

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(no_global_oom_handling)',
]
