[package]
name = "opaque_vec"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.opaque_alloc]
version = "0.1.0"
path = "../opaque_alloc"

[dependencies.opaque_blob_vec]
version = "0.1.0"
path = "../opaque_blob_vec"

[dependencies.opaque_error]
version = "0.1.0"
path = "../opaque_error"

[dev-dependencies]

[dev-dependencies.opaque_vec_testing]
version = "0.1.0"
path = "../opaque_vec_testing_support"

[dev-dependencies.criterion]
version = "0.5.1"

[features]
panic_immediate_abort = []

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(no_global_oom_handling)',
]

[[bench]]
name = "bench_opaque_vec"
harness = false
path = "benches/lib.rs"
