[package]
name = "opaque_alloc"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]

[dev-dependencies.criterion]
version = "0.6.0"

[[bench]]
name = "bench_opaque_alloc"
harness = false
path = "benches/lib.rs"
