[package]
name = "opaque_map"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.equivalent]
version = "1.0.2"
default-features = false

[dependencies.hashbrown]
version = "0.15.2"

[dependencies.indexmap]
version = "2.8.0"

[dependencies.opaque_vec]
path = "../opaque_vec"
