[package]
name = "opaque_hash"
version = "1.2.0"
edition = "2024"

[features]
default = ["std"]
std = []
nightly = []

[dependencies]

[dev-dependencies]

[dev-dependencies.criterion]
version = "0.6.0"

[[bench]]
name = "bench_hasher"
harness = false
path = "benches/lib.rs"
